package com.albertchow.lifecompass.entity;

import com.baomidou.mybatisplus.annotation.FieldFill;
import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Data;

import java.time.LocalDateTime;

/**
 * Represents one user following another user (a social "follow", separate
 * from a user following/saving a shop — see {@link ShopFollow} for that).
 * Maps to the "follow" table.
 */
@Data
@TableName("follow")
public class Follow {

    /** Primary key, auto-generated by the database. */
    @TableId(type = IdType.AUTO)
    private Long id;

    /** ID of the user who is doing the following (references user.id). */
    private Long userId;

    /** ID of the user being followed (references user.id). */
    private Long followUserId;

    /** When this follow relationship was created; filled in automatically on insert. */
    @TableField(fill = FieldFill.INSERT)
    private LocalDateTime createTime;
}
